version: '3.8'

services:
  postgres:
    image: postgres:14.1-alpine
    container_name: postgres-container
    environment:
      POSTGRES_USER: proxyuser
      POSTGRES_PASSWORD: proxypass
      POSTGRES_DB: proxydb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
